Painter
QTimeLine* Painter::animation_timer
Referenced by init_timer, setupAnimations, stop_timer.
QGraphicsItemAnimation* Painter::animation_genuine
Referenced by setupAnimations.
QGraphicsItemAnimation * Painter::animation_virt
Referenced by setupAnimations.
QBrush Painter::brush
QPen Painter::pen
QGraphicsScene* Painter::canvas
int Painter::total_animation_duration
int Painter::frames
Painter::Painter()
References DebugTools::strMsg.
Painter::Painter(QGraphicsScene *, int frame_duration, int frames, QBrush=QBrush(QColor("#b9ffd1")), QPen=QPen(Qt::black, 2))
QGraphicsItem * Painter::drawSurface(Polygon *Poly)
QGraphicsEllipseItem * Painter::drawElectron(Point *P)
Referenced by setupAnimations.
QGraphicsEllipseItem * Painter::drawVirt(Point *P)
Referenced by setupAnimations.
QGraphicsItem * Painter::drawVector(Line)
References drawLine.
QGraphicsItem * Painter::drawLine(Line)
References drawLine.
Referenced by drawArrow, drawLine, drawVector.
QGraphicsItem * Painter::drawLine(Line, QColor)
References Line::x0, Line::x1, Line::y0, Line::y1.
QGraphicsItem * Painter::drawLine(QPointF, QPointF)
References drawLine.
QGraphicsItem * Painter::drawLine(QPointF, QPointF, QColor)
QGraphicsItemGroup * Painter::drawArrow(Line, QColor)
References drawLine, Line::dx, Line::dy, Line::equation_of_self, Line::find_equationOfSelf, Line_equation::k, Line::p0, Line::p1, Physics_engine::PI, Point::rotate, Point::stat_move, Point::toQPoint.
Referenced by drawArrow.
QGraphicsItemGroup * Painter::drawArrow(Line)
References drawArrow.
void Painter::setupAnimations(Point *ElP0, Point *VirP0)
References animation_genuine, animation_timer, animation_virt, drawElectron, drawVirt, init_timer.
void Painter::init_timer()
References animation_timer, stop_timer.
Referenced by setupAnimations.
void Painter::stop_timer()
References animation_timer.
Referenced by init_timer.
QGraphicsItem * Painter::drawPoly(Polygon *, QBrush)
QGraphicsItem * Painter::drawPoly(QPolygon *, QBrush)
QGraphicsEllipseItem * Painter::drawCircle(Point *, int, QBrush)