Line
Point Line::p0
Referenced by Painter::drawArrow, Line, x0, y0.
Point Line::p1
Referenced by Painter::drawArrow, Line, x1, y1.
Line_equation Line::equation_of_self
Referenced by Painter::drawArrow, Physics_engine::find_base_of_perpendicular, find_equationOfSelf.
Line_equation Line::equation_of_perpendicular
Referenced by Physics_engine::find_base_of_perpendicular, find_equationOfPerpendicular.
Line::Line()
References p0, p1.
Referenced by extendedCopy, movedCopy.
Line::Line(Point _p0, Point _p1)
References p0, p1.
Line::Line(int _x0, int _y0, int _x1, int _y1)
References p0, p1.
Line::Line(double _x0, double _y0, double _x1, double _y1)
References p0, p1.
QLineF Line::to_qline()
References x0, x1, y0, y1.
void Line::find_equations(Point _electron)
References find_equationOfPerpendicular, find_equationOfSelf.
Referenced by Physics_engine::find_base_of_perpendicular.
void Line::find_equationOfSelf()
References equation_of_self, x0, x1, y0, y1.
Referenced by Painter::drawArrow, find_equations.
void Line::find_equationOfPerpendicular(Point _electron)
References equation_of_perpendicular, Point::x, x0, x1, Point::y, y0, y1.
Referenced by find_equations.
double Line::length()
References x0, x1, y0, y1.
double Line::square_of_length()
References x0, x1, y0, y1.
Referenced by Physics_engine::get_acceleration_mantissa.
int Line::x0()
References p0, Point::x.
Referenced by Painter::drawLine, dx, find_equationOfPerpendicular, find_equationOfSelf, length, square_of_length, to_qline.
int Line::y0()
References p0, Point::y.
Referenced by Painter::drawLine, dy, find_equationOfPerpendicular, find_equationOfSelf, length, square_of_length, to_qline.
int Line::x1()
References p1, Point::x.
Referenced by Painter::drawLine, dx, find_equationOfPerpendicular, find_equationOfSelf, length, square_of_length, to_qline.
int Line::y1()
References p1, Point::y.
Referenced by Painter::drawLine, dy, find_equationOfPerpendicular, find_equationOfSelf, length, square_of_length, to_qline.
int Line::dx()
References x0, x1.
Referenced by Painter::drawArrow, movedCopy.
int Line::dy()
References y0, y1.
Referenced by Painter::drawArrow, movedCopy.
Line Line::extendedCopy(int a)
References Line, Point::x.
Line Line::movedCopy(Line *vector)
References dx, dy, Line, Point::x.
Line Line::movedCopy(Line staticVector)
References dx, dy, Line, Point::x.
std::ostream & operator<<(std::ostream &out, Line &L)